### ISSUE TITLE
IMPORTANT PLEASE READ

### ISSUE THREAD

**Issue by OutRed** [OutRed/outred.github.io#11]
Hey Cyclokid, if you can see this, this is important. If you do not make any more commits since your last one months ago, you will lose your role as collaborator. Respond if you see this with something so I know if i should remove you or not.

**Comment by CycloKid** [comment]
sorry, i have been  busy with other things
i have found a bunch more new games to add, but im gonna need edit access again
you can find some of the new games here: [https://github.com/CycloKid?tab=repositories](https://github.com/CycloKid?tab=repositories)

**Comment by CycloKid** [comment]
I'd also like to update the cookie clicker html to a complete replica of the official game, if you want to see it then its right here: [https://cyclokid.github.io/cookieclicker/](https://cyclokid.github.io/cookieclicker/)

**Comment by CycloKid** [comment]
but it doesnt work if you put it in an iframe, so either two of these options will work
1 - Placing the cookie clicker files in a subdirectory of this repo
OR
2 - using [this html file](https://github.com/CycloKid/cookieclicker/blob/gh-pages/official-cookieclicker.html) to redirect automatically to my github page site with the game

**Comment by OutRed** [comment]
bet ok

**Comment by OutRed** [comment]
I will do it in like an hour or two. I am busy right now.
