### ISSUE TITLE
Update Mario Bros S to v0.2.0.1

### ISSUE THREAD

**Issue by CycloKid** [OutRed/outred.github.io#12]
Fork the new repo that superpi2 made here:
https://github.com/superpi2/SuperMarioBrosS-v0.2.0.1

**Comment by OutRed** [comment]
Alright, thanks just realizing now that the Mario bros I have doesn't work.

**Comment by CycloKid** [comment]
Oh wait yeah i also just realized that mine doesnt work either
]=
