### ISSUE TITLE
For CycloKid

### ISSUE THREAD

**Issue by fowntain** [OutRed/outred.github.io#18]
Hi @CycloKid! I see you used my website, [Skool](https://skool.world), as a reference. Good luck with this site, and just remember if you need any help, you have me!

Thanks,
     Dean (fowntain)

**Comment by CycloKid** [comment]
OutRed, also iframes wont unblock anything cause they are basically just the same website, but well, in another one, it does that same kinda stuff to access the site.

**Comment by fowntain** [comment]
@CycloKid @OutRed 
try using this url in your iframe: [[https://skoolgq.github.io](url)](https://skoolgq.github.io)

**Comment by OutRed** [comment]
i did not iframe the original url, i forked it on replit and removed the
replit watermark and then iframed that one.
