### ISSUE TITLE
Add Game "Idle Breakout"

### ISSUE THREAD

**Issue by CycloKid** [OutRed/outred.github.io#2]
There is a good game to put on this site, you can fork it from [https://www.github.com/SoBloxsy/idle-breakout](https://www.github.com/SoBloxsy/idle-breakout), or you can clone/download the zip file from the repository.

**Comment by OutRed** [comment]
I mainly add games using iframes. If you would like to help me add games to my site, you can paste iframe codes for games in this issue.

**Comment by CycloKid** [comment]
what should be the iframe height and width?

**Comment by OutRed** [comment]
Alright! If you want to add iframe games, just make the height and the width reasonable. I don't really care as long as its not too small. you can view other games i have iframed on my site and see the height and width for those. I don't have many those bc i recently created this repo and havent had much time to work on it. thanks for the instructions!
