### ISSUE TITLE
Add another unblocker/proxy and fix for blocked keyword

### ISSUE THREAD

**Issue by CycloKid** [OutRed/outred.github.io#20]
This one is actually replit based so you just need to fork [this project on replit](https://replit.com/@binaryperson/womginx?v=1) (Just the "Fork" button on the right side of the page) and then you can link that to an iframe on the site using this url format:
_project_._username_.repl.co
project = project name (spaces and underscores are counted as hyphens
username = replit user's username
It also works for vercel too but thats usually blocked
if you dont already have replit then you can login with github which will make it quick and easy

***IMPORTANT - Please Replace, Remove, or Prohibit use of the words "unblocked" and "proxy" as they are common keywords that are used to auto restrict sites**

**Comment by OutRed** [comment]
Yeah, I use replit all the time. I'm actually working on a chatbox in
replit, and when it is done, I am going to add it to the site under "Apps".
I actually think that the replit I have iframed now is named
"school-is-fun", so I don't see why I need to make a new one.

**Comment by b3lief** [comment]
@OutRed, most likely because it doesn't work, the unblocker on your site doesn't even respond properly.

**Comment by OutRed** [comment]
Version 3 of the site is coming out soon, probably within a week. Don't
worry, I am fixing all the bugs on the website including the unblocker, and
I will be adding multiple links for the unblocker, and adding more games.
(Like a LOT more)

**Comment by b3lief** [comment]
Greetings, @OutRed. If you want, I could become an active developer for this site. I know html, js, python, and many other languages.

**Comment by OutRed** [comment]
That would be great. Please join the Discord so you can submit your code to
help out with the site. I would love to have you helping. Thanks.
