### ISSUE TITLE
Add Subway Surfers

### ISSUE THREAD

**Issue by CycloKid** [OutRed/outred.github.io#21]
You can fork this on replit: https://replit.com/@CycloKid/Subway-Surfers-on-Replit
then go to "index.js" and replace "subsurf.cyclokid.repl.co" with your replit project site like this: Subway-Surfers-on-Replit.robertfesko.repl.co
(replace "project" with whatever your project name url part is or what you rename it to)

**Comment by OutRed** [comment]
ight
