### ISSUE TITLE
Links!

### ISSUE THREAD

**Issue by TrickJoker312** [OutRed/outred.github.io#26]
Are there any more links for this site? If so, please reply with them. I'd really appreciate it!

**Comment by OutRed** [comment]
Hello, thank you for your feedback. I will try to work on that today and
make it more accessible. If none of the links work for you I make today,
please let me know and I will do my best. I will try to make three points.

**Comment by OutRed** [comment]
I've set up a second link btw check the README.md

**Comment by TrickJoker312** [comment]
Thank you! I appreciate it!
