### ISSUE TITLE
[QUESTION]: V3

### ISSUE THREAD

**Issue by nxxh447** [OutRed/outred.github.io#27]
When will V3 be released? I am looking to contribute but if a rework is going to be released then I'll simply wait.

**Comment by OutRed** [comment]
V3 is already mostly out. The only thing that I need to do is get the
soundboard ready and one other thing. One way you can contribute is by
giving me links to repos with working game files. That would help a lot,
and you can just send the links here. Thanks for your willingness to help
out.

**Comment by TrickJoker312** [comment]
i could help with this :D

**Comment by OutRed** [comment]
Tysm!

**Comment by TrickJoker312** [comment]
You're welcome!

**Comment by OutRed** [comment]
Also, feel free to try to find game files, along with swf files. Whatever
works, but I do not do iframes. Thanks for your help.
