### ISSUE TITLE
Update Minecraft Java Web

### ISSUE THREAD

**Issue by CycloKid** [OutRed/outred.github.io#3]
Here is the link to my new updated html file
[https://raw.githubusercontent.com/cyclokid/eaglercraft/main/stable-download/Offline_Download_Version.html](https://raw.githubusercontent.com/cyclokid/eaglercraft/main/stable-download/Offline_Download_Version.html)

**Comment by OutRed** [comment]
I’ll do that soon. I’m going to be busy so give me some time.
