### ISSUE TITLE
Could I have write access to this repo?

### ISSUE THREAD

**Issue by CycloKid** [OutRed/outred.github.io#5]
I believe i could be a great asset to have for contributing on this repo.
I can make, find, fork, and add stuff to this repository that could make it much more full of games, and save lots of time for you.

**Comment by OutRed** [comment]
idk man, kinda sus. maybe

**Comment by OutRed** [comment]
If I did give you access, you would only be allowed to do these things.

1. Would ONLY be allowed to edit games.md
2. Would NOT be allowed to edit any other file.
3. Would have to run the game by me before adding it

I might add some more rules

**Comment by CycloKid** [comment]
Sure thing, if I had better permissions to easily add games for you, then I'd love to help better this repository and your development process with you.

**Comment by OutRed** [comment]
What better permissions would you like? I’m sure we can figure something out.

**Comment by CycloKid** [comment]
So that every now and then, that you could check the folder and give me feedback about your opinion on games
maybe I could find a repo that adds commenting so that we could talk without opening issues

**Comment by OutRed** [comment]
I think I will make you a collaborator. Here are the following things and restrictions you would be allowed to do and you would not be allowed to do.

1.  You would be allowed to add games. Mainly on Game.md
2. Games that you add would not allowed to contain NSFW. Any game you add MUST be appropriate.
3. When adding games, please follow my format I have already started with.
4. Make sure you edit Game.md, not Games.md. Game.md is the correct one.
5. You would be allowed to set up a new password protector

By responding to this you are accepting my policy. Before I make you a collaborator, you must agree to this.

**Comment by CycloKid** [comment]
Alright! I already know that NSFW is not allowed in github at all, so I know that _way_ out of the question
(that would be kinda ironic since github _IS A WORK SITE_)
And I have lots experience with using forks, and index.html. Which is much easier to handle IMO

**Comment by OutRed** [comment]
Whatever is easiest for you. I will probably be giving you edit access sometime tomorrow.

**Comment by OutRed** [comment]
I have just give you edit access. Don’t do anything stupid.
