### ISSUE TITLE
Use better password protector

### ISSUE THREAD

**Issue by CycloKid** [OutRed/outred.github.io#6]
This repo [here](https://github.com/chrissy-dev/protected-github-pages)
It uses a sha1 hash that translates back to your password.
You can also generate sha1 hash right here too:[https://md5decrypt.net/en/Sha1/](https://md5decrypt.net/en/Sha1/)

**Comment by OutRed** [comment]
Yeah, the password i had on there was just temporary. Thanks for the tip.


Sent from my Apple Watch

**Comment by CycloKid** [comment]
Great!
Although you might need Git to move all the files tho.
