### ISSUE TITLE
Patch Discussion

### ISSUE THREAD

**Issue by OutRed** [OutRed/outred.github.io#7]
Hey cyclokid, when you edit something or add something, anything like that, just put it here so I can see how you've improved the site.

**Comment by CycloKid** [comment]
Replaced Cookie Clicker with my own (Updated from v2.021 to v2.024

**Comment by CycloKid** [comment]
Added New Game: Arena (you might know it from scratch)

**Comment by OutRed** [comment]
yooo! how did you get it to say outred games on the loading screen for the
game Arena?? thats sick! i want that on all the games!

**Comment by CycloKid** [comment]
Its sadly only for the scratch games, but I'm sure that I could maybe find a way to apply a similar effect to some of the other games, maybe (just maybe)

**Comment by OutRed** [comment]
could you add getting over it real quick and make it say outred games as
its loading? that would be great if you could do so. i am currently getting
a new homepage designed that looks a lot like https://moyaimoment.github.io.
it will have css animations and everything. my goal in this website is to
try to get ads on it or something like that. but, outred games does not
have anything close to 50,000 page views.

**Comment by OutRed** [comment]
i also want to add "The Worlds Hardest Game". I have the .swf file for it,
but I need to figure out how to add ruffle to the repo so I the game will
work.

**Comment by CycloKid** [comment]
> i also want to add "The Worlds Hardest Game"
Im currently trying a solution, i could maybe get it into the site tommorow

**Comment by OutRed** [comment]
That would be awesome!

**Comment by CycloKid** [comment]
i found a solution, i edited the index.html file of that my repo and its now centered and (sorta) fullscreen, it fits the screen well now
I'm going to update the repo with the fixed resolution, give it a minute and try again

**Comment by CycloKid** [comment]
Hey @OutRed i also want to let you know that your replies show your name💀

**Comment by OutRed** [comment]
oh crap are you fricking kidding me

**Comment by OutRed** [comment]
well there's lots of people out there with the same name as me so you have
no idea who I am probably

**Comment by CycloKid** [comment]
Hey could tou add me to discord? My discord is in my readme so could yoh send a request there instead of reading from the issues where everyone can see?

**Comment by OutRed** [comment]
sure thing. ill do that now.

**Comment by OutRed** [comment]
I sent you a friend request. I am "USERNAME".

**Comment by CycloKid** [comment]
I recently just found [this repository](https://github.com/Skoolgq/skoolgq.github.io) that has a really polished look, maybe you could maybe take a look at it.

**Comment by OutRed** [comment]
😮😮🤯🤯🤯 a fricking unblocker???
I’m adding that to OutRed games

**Comment by CycloKid** [comment]
not exactly.. i couldn't actually find the source code myself. so you'd have to find it some other way, cause I dont have the time for scraping some kind of murder mystery [like this one](https://i.stack.imgur.com/sFOAJ.png)

**Comment by OutRed** [comment]
i found the source code im adding it today

**Comment by OutRed** [comment]
hey, thats fine, but, i do not want it to redirect to your website. i want
to keep the url the same for all the games. is there another way i can add
it?

**Comment by CycloKid** [comment]
i think you can edit the html to links that stay in the same github.io site

**Comment by CycloKid** [comment]
AHA! I got it! you can iframe [this repl](https://womginx.cyclokid.repl.co/) to the site.
Its a repl, so it might take a minute to wake, but after that, its very stable.
